services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - golang-net
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - backendtwo

  backend:
    build:
      context: ./backend
    container_name: golang-app
    networks:
      - golang-net
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_db
    depends_on:
      - mysql

  backendtwo:
    build:
      context: ./backendtwo
    container_name: golang-app-two
    networks:
      - golang-net
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - golang-net
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  golang-net:
    driver: bridge 
