# Use an official Golang image as the base image
FROM golang:1.23.4-alpine3.20

# Set the working directory inside the container
WORKDIR /app

# Copy the Go modules files first to enable caching
COPY go.mod go.sum ./

# Download the Go module dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the application
RUN go build -o main .

# Start the application
CMD ["./main"]
