name: Run Code Test

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    name: main test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.4'

    - name: Install dependencies
      run: |
        cd backend
        go mod tidy

    - name: Run tests
      run: |
        cd backend
        go test ./...
